name: maintech
services:
  # --- Service Base de Données (PostgreSQL) ---
  db:
    image: postgres:15-alpine
    container_name: maintech_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: atef*12861161 # Même mot de passe que votre config locale
      POSTGRES_DB: mainTech
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- Service Backend (FastAPI) ---
  backend:
    build: ./backend
    container_name: maintech_backend
    restart: always
    depends_on:
      - db
    environment:
      # L'URL pointe vers la base de données Neon en ligne
      - DATABASE_URL=postgresql://neondb_owner:npg_NOsRW1E0hvdg@ep-damp-paper-ap4etceh-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - GEMINI_API_KEY=AIzaSyAcSo27GWmgxFewHhFkPEE_v4G6BwStkeE
    ports:
      - "8000:8000"
    volumes:
      # Volume pour persister la base vectorielle ChromaDB et les documents
      - ./backend/app/data:/app/app/data



volumes:
  pgdata:
